#!/bin/bash

# exit status and error codes
SUCCESS=0      # success exit code
E_WRONGARGS=66 # wrong number of arguments passed to script

# exit if script is run with arguments
[[ $# -eq 0 ]] || exit "$E_WRONGARGS"

# check the exit status of pgrep kodi is zero
if [[ $(pgrep kodi) && $? -eq 0 ]]; then
	printf "%s\n" "kodi is runnning"
   sleep 5s
	printf "%s\n" "start automation script"
	# automation code goes here
   sleep 5s
   printf "%s\n" "killing kodi"
   kill -9 $(pgrep kodi)
   exit "$SUCCESS"
else
    printf "%s\n" "kodi isnt running so lets start it"
    kodi &>/dev/null &
    sleep 5s
    printf "%s\n" "start automation script"
    # automation code goes here
    sleep 5s
    printf "%s\n" "killing kodi"
    kill -9 $(pgrep kodi)
    exit "$SUCCESS"
fi
